Jenkinsfile, usabilla-react-native/package-lock.json, usabilla-react-native/package.json
This PR adds [semantic-release](https://github.com/semantic-release/semantic-release) to automate the package publishing of  `usabilla-react-native`.
=> feat(automation): add semantic-release & update jenkins

App.js, usabilla-react-native/README.md, usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.m, usabilla-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift, usabilla-react-native/src/index.js
This PR adds support for **Custom Variables** in the iOS bridge.
=> feat(custom-variables): Add support for custom variables in iOS bridge

App.js, usabilla-react-native/android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, usabilla-react-native/src/index.js
@tzengerink @Rifinio @kioli @SuzettePaeta @gPinato
=> feat(custom-variables): add Android support for custom variables

App.js, usabilla-react-native/android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, usabilla-react-native/src/index.js
@tzengerink @Rifinio @kioli @SuzettePaeta @gPinato
=> feat(campaigns): add Android support for campaigns

usabilla-react-native/README.md
@tzengerink @Rifinio @SuzettePaeta @gPinato
=> docs(readme): add readme explanation for bridge features

App.js, usabilla-react-native/README.md, usabilla-react-native/android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.m, usabilla-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift, usabilla-react-native/src/index.js
close: [SDK-977](https://usabilla.atlassian.net/browse/SDK-977)
@tzengerink @Rifinio @kioli @SuzettePaeta @gPinato
=> Feature/sdk 977/add support for custom variables

App.js, usabilla-react-native/README.md, usabilla-react-native/android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, usabilla-react-native/src/index.js
@tzengerink @Rifinio @SuzettePaeta @gPinato
=> feat(screenshot): add Android support for screenshot

App.js, usabilla-react-native/README.md, usabilla-react-native/android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.m, usabilla-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift, usabilla-react-native/src/index.js
This PR Will merge back the Campaign feature for both iOS and Android.
=> Feature/sdk 973/add support for campaigns

usabilla-react-native/README.md, usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.h, usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.m, usabilla-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift, usabilla-react-native/src/index.js
This PRs adds support for screenshot in iOS;
- allows loading a feedback form with the current view screenshot.
=> feat(screenshot) : Add screenshot support to allow loading a form

App.js, usabilla-react-native/README.md, usabilla-react-native/android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.h, usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.m, usabilla-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift, usabilla-react-native/src/index.js
This PR Will introduce the Screenshot feature for both iOS and Android.
=> Feature/sdk 972/add support for screenshot

usabilla-react-native/ios/ReactNativeUsabilla/ReactNativeUsabilla.m, usabilla-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift
Fix bug: passive form not showing if the SDK is initialized with null.
=> fix(passive-forms): passive form not showing when initialized with null

UsabillaSampleApp/App.js, UsabillaSampleApp/package-lock.json, UsabillaSampleApp/package.json, android/build.gradle, android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, src/index.js
Closes ticket [BLISS-171](https://usabilla.atlassian.net/browse/BLISS-171)
Align RN bridge to our latest Android SDK version (5.2.1) public interface signature apart from:
- passing a screenshot image
- submission callback
- enable dev debugging
- preload forms
- theme configuration
=> fix(interface): Align android method signatures

package-lock.json
Fix vulnerable dependency deep-extend (running `npm audit fix` command)
[BLISS-207](https://usabilla.atlassian.net/browse/BLISS-207)
=> fix(dependecy): upgraded deep-extend

Jenkinsfile
Fix the CD bug which prevented the repo to be published automatically to `npm` upon merging PRs in the `master` branch
=> chore(deployment): Fix NPM token issue

UsabillaSampleApp/ios/RNUsabilla/Info.plist
- Add iOS permission for camera usage
=> feat(permission): add iOS permission for camera usage

package.json, usabilla-react-native.podspec
Add Podspec to support RN 0.6.0 autolinking
=> [iOS]Add podspec to support RN 0.6.0 autolinking

ios/ReactNativeUsabilla/ReactNativeUsabilla.m, ios/ReactNativeUsabilla/UsabillaInterface.swift
- Changed result type for mood rating callback on formDidClose
=> fix(ios): update callback method for ratings

android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, ios/ReactNativeUsabilla/ReactNativeUsabilla.m, ios/ReactNativeUsabilla/UsabillaBridge.swift, src/index.js
- Added support for Form Close event
- Added support for Campaign Close event
=> Task - Bliss 84 - Add support sdk callbacks

README.md
- Added new callback methods to the guide
- Added explanation about Campaigns and Forms to the guide
=> chore(readme): Update documentation

UsabillaSampleApp/yarn.lock, ios/ReactNativeUsabilla.xcodeproj/project.pbxproj, yarn.lock
- Update reference for adding UsabillaBridge and removing UsabillaInterface.
=> fix(ios): Update reference

README.md, UsabillaSampleApp/yarn.lock, ios/ReactNativeUsabilla.xcodeproj/project.pbxproj, ios/ReactNativeUsabilla/ReactNativeUsabilla.m, ios/ReactNativeUsabilla/UsabillaBridge.swift, src/index.js, yarn.lock
- Added support for load localisation via passing custom file name
=> feat(ios): Add support for load localisation via custom file

UsabillaSampleApp/android/app/build.gradle, android/build.gradle, android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java
- Update android sdk V7+
- Add android-x support
=> Task/bliss 622/androidx support

UsabillaSampleApp/package.json
- Update dependencies to the latest version
- Fix android sample app
=> fix(sample): Update sample android app to RN v0.63.2

usabilla-react-native.podspec
Crash on ios 13 & above , after dismissing campaign, and rotating device 
Build with Xcode 12.0
=> Update podspec to support v6.5.0

android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, ios/ReactNativeUsabilla/ReactNativeUsabilla.m, ios/ReactNativeUsabilla/UsabillaBridge.swift, src/index.js, yarn.lock
- Added support for preloading passive forms
=> feat(interface): add preloading capabilities for passive forms

UsabillaSampleApp/yarn.lock, package.json, src/index.d.ts, usabilla-react-native.podspec, yarn.lock
- Updated typescript Support
- Excluded architecture arm64 for ios simulators
=> Feature/bliss 654/add typescript support

README.md, UsabillaSampleApp/App.js, ios/ReactNativeUsabilla/UsabillaBridge.swift
Closes: [BLISS-537](https://usabilla.atlassian.net/browse/BLISS-537)
Reviewers: @usabilla/bliss
Custom Variable supports string only.
=> fix(interface) : Custom variable to support string only

UsabillaSampleApp/android/app/build.gradle, UsabillaSampleApp/android/build.gradle
Fixes a crash at startup on Android devices running Android API below 27
=> Fix Java8 compatibility

.script/commit_check.sh, package.json, yarn.lock
Add commit message check script
=> chore(githook): add githook to check commit message

UsabillaSampleApp/package.json, UsabillaSampleApp/yarn.lock, android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, ios/ReactNativeUsabilla/ReactNativeUsabilla.m, ios/ReactNativeUsabilla/UsabillaBridge.swift, src/index.d.ts, src/index.js
- Remove default ios debug mode
- Add method to toggle debug mode
=> feat(interface): add debug mode

UsabillaSampleApp/yarn.lock, android/build.gradle, yarn.lock
- Update Gradle to use specific Android SDK v7.4.0
=> fix(android) : update gradle to use sdk v7.4.0

UsabillaSampleApp/android/app/build.gradle, UsabillaSampleApp/android/app/src/main/AndroidManifest.xml, UsabillaSampleApp/android/build.gradle, UsabillaSampleApp/android/gradle.properties, UsabillaSampleApp/android/gradle/wrapper/gradle-wrapper.properties, UsabillaSampleApp/package.json, yarn.lock
fix(android): update dependencies and gradle for sample app
=> Task/gfpsdk 1072/fix sample app

UsabillaSampleApp/App.js, UsabillaSampleApp/android/app/build.gradle, UsabillaSampleApp/android/app/src/main/AndroidManifest.xml, UsabillaSampleApp/android/build.gradle, UsabillaSampleApp/android/gradle.properties, UsabillaSampleApp/android/gradle/wrapper/gradle-wrapper.properties, UsabillaSampleApp/package.json, UsabillaSampleApp/yarn.lock, android/src/main/java/com/usabilla/reactnative/ubform/UsabillaBridge.java, src/index.d.ts, src/index.js, yarn.lock
fix(android): Added ready callback
=> Fix/gfpsdk 1128/add ready callback

UsabillaSampleApp/Gemfile.lock, UsabillaSampleApp/package-lock.json, package.json, yarn.lock
Closes: [GFPSDK-1153](https://momentiveai.atlassian.net/browse/GFPSDK-1153)
Reviewers: @usabilla/bliss
- Remove post-install script
=> fix(build): remove post install script

README.md
Changed the support text in the read me
=> Uodate support section of readme

UsabillaSampleApp/Gemfile.lock, UsabillaSampleApp/package-lock.json, yarn.lock
- Releasing v1.0.7
- Merge all Dependbots commits
=> Mobile 14284
